apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always

          readinessProbe:
          httpGet:
            path: /grid
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /grid
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}

          ports:
            - containerPort: {{ .Values.backend.port }}

          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_PORT

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password