apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelwar-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"

spec:
  ingressClassName: nginx

  rules:
    - host: localhost
      http:
        paths:

          # FRONTEND
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          # SOCKET.IO
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

          # API
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80