redis:
  image: redis:7
  port: 6379

  persistence:
    enabled: true
    size: 1Gi

  auth:
    password: ""

backend:
  image: flyzeur163/pixelwar-backend
  replicas: 2
  port: 80

frontend:
  image: flyzeur163/pixelwar-frontend
  replicas: 2
  port: 80

ingress:
  host: localhost

networkPolicy:
  enabled: true