redis:
  image: redis:7
  port: 6379

  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

  auth:
    password: ""

backend:
  image: flyzeur163/pixelwar-backend
  replicas: 2
  port: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

frontend:
  image: flyzeur163/pixelwar-frontend
  replicas: 2
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

ingress:
  host: localhost

networkPolicy:
  enabled: true