name: CI/CD Pixel War

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: pixelwar-backend
  FRONTEND_IMAGE: pixelwar-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # CHECKOUT CODE
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # LOGIN DOCKER HUB
      # -------------------------
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------------------------
      # GENERATE VERSION TAG
      # -------------------------
      - name: Set image tag
        id: tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # -------------------------
      # BUILD/PUSH BACKEND
      # -------------------------
      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE:$TAG ./backend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE:$TAG ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE:latest

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE:latest

      # -------------------------
      # PUSH/BUILD  FRONTEND
      # -------------------------
      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE:$TAG ./frontend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE:$TAG ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE:latest
      
      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE:latest

      - name: Summary
        run: |
          echo "Build & Push completed"
          echo "Backend: ${{ secrets.DOCKERHUB_USERNAME }}/$BACKEND_IMAGE:$TAG"
          echo "Frontend: ${{ secrets.DOCKERHUB_USERNAME }}/$FRONTEND_IMAGE:$TAG"

  # bootstrap:
  #   needs: build-and-push
  #   runs-on: self-hosted

  #   steps:
  #     - name: Create Kind cluster
  #       shell: pwsh
  #       run: |
  #         kind get clusters | Select-String "pixelwar-cluster"
  #         if ($LASTEXITCODE -ne 0) {
  #           kind create cluster --config ./k8s/kind-config.yaml
  #         }

  #     - name: Install Ingress Nginx
  #       shell: pwsh
  #       run: |
  #         kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/cloud/deploy.yaml

  deploy:
    needs: [build-and-push]
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # VERIFY CLUSTER ACCESS
      # -------------------------
      - name: Check Kubernetes
        shell: pwsh
        run: kubectl get nodes

      - name: Deploy Helm
        shell: pwsh
        run: |
          helm upgrade --install pixelwar ./helm `
            --namespace pixelwar `
            --create-namespace `
            --set redis.auth.password=${{ secrets.REDIS_PASSWORD }}

      # -------------------------
      # HELM DEPLOY
      # -------------------------
      - name: Deploy Pixel War (Helm)
        shell: pwsh
        run: |
          helm upgrade --install pixelwar ./helm `
            --namespace pixelwar `
            --create-namespace `
            --set backend.image=${{ secrets.DOCKERHUB_USERNAME }}/pixelwar-backend:latest `
            --set frontend.image=${{ secrets.DOCKERHUB_USERNAME }}/pixelwar-frontend:latest

      # -------------------------
      # CHECK DEPLOYMENT
      # -------------------------
      - name: Verify deployment
        shell: pwsh
        run: |
          kubectl get pods -n pixelwar
          kubectl get svc -n pixelwar